# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PipelineMonitor
                                 A QGIS plugin
 用于监控管线测试桩电压并进行可视化展示
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-30
        copyright            : (C) 2025 by LSY
        email                : 2256124857@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PipelineMonitor class from file PipelineMonitor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pipeline_monitor import PipelineMonitor
    return PipelineMonitor(iface)
